// Browser regression for shipped cinematic player; node tests/vr/cinematic-browser.cjs.
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const {chromium}=require('C:/Users/milin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../../public');
const server=http.createServer((req,res)=>{if(req.url==='/__cinematic_test'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<!doctype html><title>Cinematic test</title>');return;}let file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end();return;}let size=fs.statSync(file).size,type=file.endsWith('.mp3')?'audio/mpeg':file.endsWith('.webm')?'video/webm':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html';let range=req.headers.range;if(range){let [s,e]=range.replace('bytes=','').split('-').map(Number),end=Math.min(e||size-1,size-1);res.writeHead(206,{'Content-Type':type,'Content-Range':`bytes ${s}-${end}/${size}`,'Accept-Ranges':'bytes','Content-Length':end-s+1});fs.createReadStream(file,{start:s,end}).pipe(res);}else{res.writeHead(200,{'Content-Type':type,'Content-Length':size,'Accept-Ranges':'bytes'});fs.createReadStream(file).pipe(res);}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=process.env.REN_CINEMATIC_BASE||`http://127.0.0.1:${server.address().port}`;let browser;
try{browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage();await page.route('**/__cinematic_test',r=>r.fulfill({status:200,contentType:'text/html',body:'<!doctype html><title>Cinematic test</title>'}));let errors=[];page.on('pageerror',e=>errors.push(e.message));
async function setup(width=1280){await page.setViewportSize({width,height:720});await page.goto(base+'/__cinematic_test');await page.setContent(`<link rel="stylesheet" href="${base}/vr/vr.css"><div id="frame" style="position:relative;width:100%;height:500px"></div>`);await page.addScriptTag({url:base+'/vr/vr-audio.js'});await page.addScriptTag({url:base+'/vr/vr-cinematic.js'});await page.evaluate(()=>{window.calls=[];window.testAudio=TVBAudio;testAudio.setMuted(false);testAudio.setLevel('music',.6);window.start=(name='Garchomp')=>window.player=TVBCinematic.play(document.querySelector('#frame'),{id:'test',fainted:[name]},window.testAudio,reason=>calls.push(reason));});}
await setup();assert.equal(await page.evaluate(()=>TVBCinematic.select({fainted:['Floette-Eternal']}).src.endsWith('floetteeternal.webm')),true);assert.equal(await page.evaluate(()=>TVBCinematic.select({fainted:['Pikachu']})),null);
for(let name of ['Floette-Eternal','Basculegion','Kingambit','Dragonite','Garchomp','Sneasler']){let src=await page.evaluate(name=>TVBCinematic.select({fainted:[name]}).src,name);let response=await page.request.get(base+src,{headers:{Range:'bytes=0-31'}});assert.ok([200,206].includes(response.status()));assert.ok(response.headers()['content-type'].includes('video/webm'));assert.equal((await response.body()).subarray(0,4).toString('hex'),'1a45dfa3');}
await page.evaluate(()=>start());await page.waitForFunction(()=>document.querySelector('video').currentTime>.2);assert.equal(await page.evaluate(()=>testAudio.recording.current.volume),.6);
await page.evaluate(()=>{testAudio.settings.muted=true;testAudio.settings.music=.25});await page.waitForFunction(()=>document.querySelector('video').muted&&testAudio.recording.current.muted&&testAudio.recording.current.volume===.25);
await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});assert.equal(await page.evaluate(()=>document.querySelector('video').paused),true);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'))});await page.waitForFunction(()=>!document.querySelector('video').paused);
await page.evaluate(()=>{player.skip();player.skip()});assert.deepEqual(await page.evaluate(()=>calls),['skipped']);assert.equal(await page.locator('video').count(),0);assert.equal(await page.evaluate(()=>testAudio.recording.current.currentTime>=38),true);assert.equal(await page.evaluate(()=>testAudio.recording.current.paused),false);
await page.evaluate(()=>{calls=[];start('Kingambit');player.cancel();player.skip()});assert.deepEqual(await page.evaluate(()=>calls),[]);
await page.evaluate(()=>{calls=[];start('Pikachu')});await page.waitForFunction(()=>calls.length===1);assert.deepEqual(await page.evaluate(()=>calls),['unavailable']);
await page.route('**/ren-38-garchomp.webm',r=>r.fulfill({status:404}));await page.evaluate(()=>{calls=[];start()});await page.waitForFunction(()=>calls.length===1);assert.deepEqual(await page.evaluate(()=>calls),['unavailable']);await page.unroute('**/ren-38-garchomp.webm');
await setup();await page.evaluate(()=>{HTMLMediaElement.prototype.play=()=>Promise.reject(new DOMException('gesture needed','NotAllowedError'));start()});await page.getByRole('button',{name:'Play cutscene',exact:true}).waitFor({state:'visible'});await page.evaluate(()=>player.skip());assert.deepEqual(await page.evaluate(()=>calls),['skipped']);
await setup(360);await page.evaluate(()=>{testAudio.settings.muted=true;start('Sneasler')});await page.waitForFunction(()=>document.querySelector('video').currentTime>.2);assert.equal(await page.evaluate(()=>document.querySelector('.tvb-cinematic').getBoundingClientRect().right<=innerWidth),true);await page.locator('.tvb-cinematic-controls button').last().press('Enter');assert.deepEqual(await page.evaluate(()=>calls),['skipped']);
await setup();await page.evaluate(()=>start('Dragonite'));await page.waitForFunction(()=>document.querySelector('video').currentTime>.2);if(!process.env.REN_FULL_LENGTH)await page.evaluate(()=>{testAudio.recording.current.currentTime=37.8});await page.waitForFunction(()=>calls.length===1,null,{timeout:45000});assert.equal(await page.evaluate(()=>testAudio.recording.current.currentTime>=38&&!testAudio.recording.current.paused),true);assert.deepEqual(await page.evaluate(()=>calls),['ended']);assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: six remote assets, species selection, invalid data, mute/volume, background pause/resume, duplicate skip, cancellation, missing video, autoplay denial, mobile/keyboard, actual video completion, no page errors');
await setup();
for(let f of ['vr-core.js','vr-art.js','vr-game.js','vr-setup.js','vr-field.js','vr-battle.js'])await page.addScriptTag({url:base+'/vr/'+f});
await page.evaluate(async()=>{
  const raw={};for(let f of ['dex','species','sets','learnsets','items'])raw[f]=await(await fetch('/vr/'+f+'.json')).json();
  const {G,C}=TVB;G.cat=C.catalog(raw);G.draft=C.blankDraft();for(let id of ['dragonite','garchomp'])G.draft.party=C.addMember(G.cat,G.draft.party,G.cat.byId[id]).party;
  G.root=document.querySelector('#frame');G.root.classList.add('tvb');G.name='Tester';G.state='preview';
  window.workerMessages=[];window.Worker=class{constructor(){window.testWorker=this}postMessage(msg){workerMessages.push(msg);if(msg.t==='start')queueMicrotask(()=>this.onmessage({data:{t:'escalation',id:'real-dispatch-test',fainted:['Kingambit'],battleId:msg.battleId}}))}terminate(){}};
  TVB.go('battle',{seed:42});
});
await page.evaluate(()=>{for(const p of document.querySelectorAll('.tvb-health-pair')){for(const box of p.querySelectorAll('.tvb-hpbox')){box.hidden=false;box.innerHTML='<div>POKÉMON LV50</div><div>HP 100%</div>'}p.querySelector('.tvb-left').innerHTML='<span></span>'.repeat(4)}});
for(const width of [1280,360]){await page.setViewportSize({width,height:720});assert.equal(await page.evaluate(()=>[...document.querySelectorAll('.tvb-health-pair')].every(p=>{let [a,b]=p.querySelectorAll('.tvb-hpslot'),dots=p.querySelector('.tvb-left'),r=p.getBoundingClientRect(),d=dots.getBoundingClientRect();let stage=p.closest('.tvb-stage').getBoundingClientRect(),enemy=p.classList.contains('tvb-health-pair--p2');let horizontal=enemy?r.left-stage.left:stage.right-r.right,vertical=enemy?r.top-stage.top:stage.bottom-r.bottom;return Math.abs(b.getBoundingClientRect().top-a.getBoundingClientRect().bottom-4)<1&&(enemy?d.left>r.right:d.right<r.left)&&d.left>=stage.left&&d.right<=stage.right&&Math.abs(horizontal-vertical)<1&&Math.abs(horizontal-8)<1&&getComputedStyle(dots).flexDirection==='column'})),true)}
await page.setViewportSize({width:1280,height:720});
await page.waitForSelector('.tvb-cinematic video');assert.equal(await page.locator('.tvb-cinematic video').getAttribute('src'),'/assets/vr/cinematics/ren-v1/ren-38-kingambit.webm');
await page.locator('.tvb-cinematic-controls button').last().press('Enter');
await page.waitForFunction(()=>workerMessages.some(m=>m.t==='resume'));assert.equal(await page.evaluate(()=>workerMessages.filter(m=>m.t==='resume').length),1);assert.equal(await page.locator('.tvb-frame').getAttribute('data-phase'),'stadium');assert.equal(await page.evaluate(()=>TVBAudio.recording.current.currentTime>=38&&!TVBAudio.recording.current.paused),true);
await page.evaluate(()=>{testWorker.onmessage({data:{t:'escalation',id:'real-dispatch-test',fainted:['Kingambit']}})});await page.waitForTimeout(100);assert.equal(await page.locator('.tvb-cinematic').count(),0);assert.equal(await page.evaluate(()=>workerMessages.filter(m=>m.t==='resume').length),1);await page.evaluate(()=>testWorker.onmessage({data:{t:'log',lines:['|-fieldstart|move: Misty Terrain|[from] ability: Misty Surge','|-weather|Sandstorm']}}));
await page.waitForFunction(()=>document.querySelector('.tvb-stage').dataset.terrain==='mistyterrain'&&document.querySelector('.tvb-stage').dataset.weather==='sandstorm');
await page.evaluate(()=>VictoryRoad.dispose());assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: actual battle handler selects payload species, skip resumes worker exactly once, stadium persists, duplicate escalation ignored, disposal');
// Check the full backdrop and platform grounding at wide, standard and phone proportions.
for(const [width,height] of [[1280,440],[800,450],[360,420]])for(const phase of ['court','stadium']){
 await page.setViewportSize({width,height:Math.max(height,720)});
 await page.evaluate(({width,height,phase})=>{document.body.innerHTML=`<div class="tvb-frame" data-phase="${phase}" style="width:${width-40}px;height:${height}px;flex:none"><div class="tvb-stage"></div></div>`;let stage=document.querySelector('.tvb-stage');stage.innerHTML=TVBArt.arena(phase)+['p2a','p2b','p1a','p1b'].map((pos,i)=>`<div class="tvb-spot tvb-spot--${pos}"><span class="tvb-platform"></span><img class="tvb-mon-sprite" src="/assets/vr/sprites/${i<2?'front':'back'}/${['kingambit','sneasler','dunsparce','meowscarada'][i]}.png"></div>`).join('');},{width,height,phase});
 assert.equal(await page.locator('svg').getAttribute('preserveAspectRatio'),'none');
 assert.equal(await page.evaluate(()=>{let s=document.querySelector('.tvb-stage').getBoundingClientRect();return [...document.querySelectorAll('.tvb-platform')].every(p=>{let r=p.getBoundingClientRect();return r.top>s.top+s.height*.49&&r.bottom<=s.bottom&&r.left>=s.left&&r.right<=s.right})}),true);
 if(process.env.REN_LAYOUT_SCREENSHOTS)await page.locator('.tvb-frame').screenshot({path:process.env.REN_LAYOUT_SCREENSHOTS+`/${phase}-${width}.png`});
}
console.log('PASS: court and stadium backdrop retained; four platforms grounded at wide, standard and phone sizes');
await page.evaluate(()=>{window.field=TVBField.mount(document.querySelector('.tvb-stage'));field.update('|-fieldstart|move: Misty Terrain|[from] ability: Misty Surge');field.update('|-weather|Sandstorm')});
assert.equal(await page.locator('.tvb-field-label').textContent(),'Sandstorm · Misty Terrain');
for(const terrain of ['Grassy Terrain','Electric Terrain','Psychic Terrain','Misty Terrain']){await page.evaluate(terrain=>field.update('|-fieldstart|move: '+terrain),terrain);assert.equal(await page.locator('.tvb-stage').getAttribute('data-terrain'),terrain.toLowerCase().replaceAll(' ',''))}
await page.evaluate(()=>{field.update('|-fieldstart|move: Trick Room');field.update('|-fieldend|move: Grassy Terrain')});assert.equal(await page.locator('.tvb-stage').getAttribute('data-terrain'),'mistyterrain');
for(const weather of ['RainDance','SunnyDay','Sandstorm','Snow','Snowscape','Hail','PrimordialSea','DesolateLand','DeltaStream']){await page.evaluate(weather=>{field.update('|-weather|'+weather);field.update('|-weather|'+weather+'|[upkeep]')},weather);assert.equal(await page.locator('.tvb-stage').getAttribute('data-weather'),weather.toLowerCase())}
await page.evaluate(()=>{field.update('|-weather|none');field.update('|-fieldend|move: Misty Terrain')});assert.equal(await page.locator('.tvb-field-label').isVisible(),false);assert.equal(await page.locator('.tvb-stage').getAttribute('data-weather'),'');
await page.evaluate(()=>{document.querySelector('.tvb-stage').classList.add('tvb','is-reduced');field.update('|-weather|Sandstorm')});assert.equal(await page.locator('.tvb-field-weather i').first().evaluate(e=>getComputedStyle(e).animationName),'none');await page.evaluate(()=>field.dispose());assert.equal(await page.locator('.tvb-field-weather').count(),0);
console.log('PASS: actual engine log dispatch, four terrains, nine weather IDs, coexistence, replacement, unrelated fields, expiry, upkeep, reduced motion and cleanup');

}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
